name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
  pull_request:
    branches:
    - main
    paths:
    - '**.swift'
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build

  linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["swift:5.4", "swift:5.5", "swift:5.6"]
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.swift }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: swift build
